jenkins:
  remotingSecurity:
    enabled: true
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  numExecutors: 1
  scmCheckoutRetryCount: 4
  mode: NORMAL
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Workspace"
              - "Job/Build"
            assignments:
              - "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Workspace"
              - "Job/Create"
              - "Job/Delete"
              - "Job/Configure"
              - "Job/Cancel"
              - "Job/Move"
              - "Job/Build"
            assignments:
              - "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Workspace"
            assignments:
              - "nasso"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: chocolateen
         name: Hugo
         password: ${USER_CHOCOLATEEN_PASSWORD}
       - id: vaugie_g
         name: Garance
         password: ${USER_VAUGIE_G_PASSWORD}
       - id: i_dont_know
         name: Jeremy
         password: ${USER_I_DONT_KNOW_PASSWORD}
       - id: nasso
         name: Nassim
         password: ${USER_NASSO_PASSWORD}

jobs:
- script: >
      folder('Tools') {
        description('Folder for miscellaneous tools.')
      }

      job('Tools/clone-repository') {
        wrappers {
          preBuildCleanup {
              cleanupParameter('CLEANUP')
          }
        }
        parameters {
          stringParam("GIT_REPOSITORY_URL", "", "Git URL of the repository to clone")
        }
        scm {
          git {
            remote {
              url('\$GIT_REPOSITORY_URL')
            }
          }
        }
      }


      job('Tools/SEED'){
        parameters {
          stringParam("GITHUB_NAME", "", 'GitHub repository owner/repo_name (e.g.: "EpitechIT31000/chocolatine")')
          stringParam("DISPLAY_NAME", "", "Display name for the job")
        }
        steps {
          dsl {
            text('job ("\$DISPLAY_NAME") {\n\twrappers {\n\t\tpreBuildCleanup {\n\t\t\tcleanupParameter(\'CLEANUP\')\n\t\t}\n\t}\n\tscm {\n\t\tgit {\n\t\t\tremote {\n\t\t\t\turl(\"\$GITHUB_NAME\")\n\t\t\t}\n\t\t}\n\t}\n}')
          }
        }
      }
